ITBedrijfProject/Models/Register.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ITBedrijfProject.Models
{
    public class Register
    {
        public int Id { get; set; }

        [Required]
        [DisplayName("Register name")]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 2)]

        public string RegisterName { get; set; }

        [Required]
        [DisplayName("Device")]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 2)]

        public string Device { get; set; }

        [Required]
        [DisplayName("Purchase date")]
        public DateTime PurchaseDate { get; set; }

        [Required]
        [DisplayName("Expires date")]
        public DateTime ExpiresDate { get; set; }
    }
}

ITBedrijfProject/Controllers/VerenigingController.cs
using ITBedrijfProject.DataAcces;
using ITBedrijfProject.Models;
using ITBedrijfProject.PresentationModels;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ITBedrijfProject.Controllers
{
    public class VerenigingController : Controller
    {
        // GET: Vereniging
        public ActionResult Index()
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            List<Organisation> organisations = DAOrganisation.GetOrganisations();

            ViewBag.Organisations = organisations;

            return View();
        }

        [HttpGet]
        public ActionResult NewOrganisation()
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            //var context = new ApplicationDbContext();
            //ViewBag.Users = context.Users;
            return View();
        }

        [HttpPost]
        public ActionResult NewOrganisation(PMOrganisation organisation)
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            if (ModelState.IsValid)
            {
                if (DAOrganisation.InsertOrganisation(organisation) < 0) return View(organisation);
                return RedirectToAction("Index");
            }
            return View(organisation);
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            Organisation organisation = DAOrganisation.GetOrganisationById(id);
            ViewBag.Organisation = organisation;
            ViewBag.Id = id;
            return View(organisation);
        }

        [HttpPost]
        public ActionResult Details()
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            return View("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            PMOrganisation organisation = DAOrganisation.GetOrganisationById(id);
            ViewBag.Organisation = organisation;
            ViewBag.Id = id;
            return View(organisation);
        }

        [HttpPost]
        public ActionResult Edit(PMOrganisation organisation, int id)
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            if (ModelState.IsValid)
            {
                DAOrganisation.UpdateOrganisation(id, organisation);
                return RedirectToAction("Index");
            }
            return RedirectToAction("Edit", new { organisation = organisation, id = id });


        }

        [HttpGet]
        public ActionResult Register(int id)
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            ViewBag.Register = DAOrganisationRegister.GetOrganisationRegisterById(id);
            ViewBag.Organisation = DAOrganisation.GetOrganisationById(id);
            return View();
        }

        [HttpPost]
        public ActionResult Register()
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            return RedirectToAction("Index");


        }

        [HttpGet]
        public ActionResult NewRegister(int id)
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            PMOrganisationRegister organisationRegister = new PMOrganisationRegister();
            organisationRegister.NewRegister = new MultiSelectList(DARegister.GetRegisters(), "Id", "RegisterName", "Device");
            organisationRegister.OrganisationID = id;
            ViewBag.Organisation = DAOrganisation.GetOrganisationById(id);
            return View(organisationRegister);
        }

        [HttpPost]
        public ActionResult NewRegister(int organisationID, int registerID, DateTime FromDate, DateTime FromTime, DateTime UntilDate, DateTime UntilTime)
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            if (FromDate >= UntilDate) return RedirectToAction("Register", new { id = organisationID });
            OrganisationRegister organisationRegister = new OrganisationRegister();
            organisationRegister.OrganisationID = organisationID;
            organisationRegister.RegisterID = registerID;
            organisationRegister.FromDate = new DateTime(FromDate.Year, FromDate.Month, FromDate.Day, FromTime.Hour, FromTime.Minute, 0);
            organisationRegister.UntilDate = new DateTime(UntilDate.Year, UntilDate.Month, UntilDate.Day, UntilTime.Hour, UntilTime.Minute, 0);

            DAOrganisationRegister.InsertOrganisationRegister(organisationRegister);
            return RedirectToAction("Register", new { id = organisationID });
        }

        [HttpGet]
        public ActionResult EditRegister(int organisationID, int registerID)
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            PMOrganisationRegister organisationRegister = new PMOrganisationRegister();
            organisationRegister.NewOrganisation = new MultiSelectList(DAOrganisation.GetOrganisations(), "Id", "OrganisationName");
            OrganisationRegister or = DAOrganisationRegister.GetOrganisationRegisterByIds(organisationID, registerID);
            organisationRegister.Device = or.Device;
            organisationRegister.FromDate = or.FromDate;
            organisationRegister.Login = or.Login;
            organisationRegister.OrganisationID = or.OrganisationID;
            organisationRegister.OrganisationName = or.OrganisationName;
            organisationRegister.RegisterID = or.RegisterID;
            organisationRegister.RegisterName = or.RegisterName;
            organisationRegister.UntilDate = or.UntilDate;

            ViewBag.Organisation = DAOrganisation.GetOrganisationById(organisationID);
            ViewBag.oldId = organisationID;
            return View(organisationRegister);
        }

        [HttpPost]
        public ActionResult EditRegister(int oldOrganisationID, int organisationID, DateTime fromDate, DateTime untilDate, int registerID)
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            OrganisationRegister organisationRegister = DAOrganisationRegister.GetOrganisationRegisterByIds(organisationID, registerID);
            organisationRegister.FromDate = fromDate;
            organisationRegister.OrganisationID = organisationID;
            organisationRegister.RegisterID = registerID;
            organisationRegister.UntilDate = untilDate;
            DAOrganisationRegister.UpdateOrganisationRegister(oldOrganisationID, organisationRegister);
            return RedirectToAction("Register", new { id = oldOrganisationID });
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            Organisation organisation = DAOrganisation.GetOrganisationById(id);
            return View(organisation);
        }

        //Dit wordt uitgevoerd wanneer er op de deleteknop gedrukt wordt 
        [HttpPost]
        public ActionResult DeleteItem(int Id)
        {

            DAOrganisation.DeleteOrganisation(Id);

            return RedirectToAction("Index");


        }
    
    }
}

ITBedrijfProject/Views/Vereniging/Delete.cshtml
@model ITBedrijfProject.Models.Organisation

<h2>Do you want to delete this organisation?</h2>

@using (Html.BeginForm("DeleteItem", "Vereniging", FormMethod.Post))
{
    @Html.HiddenFor(a => a.Id)
    <table>
        <tr>
            <td>Gegevens</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.OrganisationName)</td>
            <td>@Html.ValueFor(a => a.OrganisationName)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Login)</td>
            <td>@Html.ValueFor(a => a.Login)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Password)</td>
            <td>@Html.ValueFor(a => a.Password)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Address)</td>
            <td>@Html.ValueFor(a => a.Address)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Email)</td>
            <td>@Html.ValueFor(a => a.Email)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Phone)</td>
            <td>@Html.ValueFor(a => a.Phone)</td>
        </tr>

        <tr>
            <td>Database Gegevens</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.DbName)</td>
            <td>@Html.ValueFor(a => a.DbName)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.DbLogin)</td>
            <td>@Html.ValueFor(a => a.DbLogin)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.DbPassword)</td>
            <td>@Html.ValueFor(a => a.DbPassword)</td>
        </tr>
        <tr>
            <td>
                <a href="/Vereniging/Index">
                    <input type="button" value="Back" />
                </a>
            </td>
            <td><input type="submit" value="Delete" /></td>

        </tr>
    </table>

    
}

ITBedrijfProject/Views/Vereniging/Details.cshtml
@model ITBedrijfProject.Models.Organisation

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

@using (Html.BeginForm("Index", "Vereniging", FormMethod.Post))
{
    <table>
        <tr>
            <td>Gegevens</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.OrganisationName)</td>
            <td>@Html.ValueFor(a => a.OrganisationName)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Login)</td>
            <td>@Html.ValueFor(a => a.Login)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Password)</td>
            <td>@Html.ValueFor(a => a.Password)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Address)</td>
            <td>@Html.ValueFor(a => a.Address)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Email)</td>
            <td>@Html.ValueFor(a => a.Email)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Phone)</td>
            <td>@Html.ValueFor(a => a.Phone)</td>
        </tr>
        
        <tr>
            <td>Database Gegevens</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.DbName)</td>
            <td>@Html.ValueFor(a => a.DbName)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.DbLogin)</td>
            <td>@Html.ValueFor(a => a.DbLogin)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.DbPassword)</td>
            <td>@Html.ValueFor(a => a.DbPassword)</td>
        </tr>
        
    </table>

    <br />
    <input type="submit" name="Back" value="Back" />
}

ITBedrijfProject/Views/Vereniging/Edit.cshtml
@model ITBedrijfProject.PresentationModels.PMOrganisation

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Vereniging", FormMethod.Post))
{
    @Html.HiddenFor(a => a.Id);
    <table>
        <tr>
            <td>Persoonlijke Gegevens</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.OrganisationName)</td>
            <td>@Html.TextBoxFor(a => a.OrganisationName)</td>
            @Html.ValidationMessageFor(a => a.OrganisationName)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Login)</td>
            <td>@Html.TextBoxFor(a => a.Login)</td>
            @Html.ValidationMessageFor(a => a.Login)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Password)</td>
            <td>@Html.TextBoxFor(a => a.Password)</td>
            @Html.ValidationMessageFor(a => a.Password)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.ControlPassword)</td>
            <td>@Html.PasswordFor(a => a.ControlPassword)</td>
            @Html.ValidationMessageFor(a => a.ControlPassword)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Address)</td>
            <td>@Html.TextBoxFor(a => a.Address)</td>
            @Html.ValidationMessageFor(a => a.Address)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Email)</td>
            <td>@Html.TextBoxFor(a => a.Email)</td>
            @Html.ValidationMessageFor(a => a.Email)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Phone)</td>
            <td>@Html.TextBoxFor(a => a.Phone)</td>
            @Html.ValidationMessageFor(a => a.Phone)
        </tr>

        <tr>
            <td>Database Gegevens</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.DbName)</td>
            <td>@Html.TextBoxFor(a => a.DbName)</td>
            @Html.ValidationMessageFor(a => a.DbName)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.DbLogin)</td>
            <td>@Html.TextBoxFor(a => a.DbLogin)</td>
            @Html.ValidationMessageFor(a => a.DbLogin)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.DbPassword)</td>
            <td>@Html.TextBoxFor(a => a.DbPassword)</td>
            @Html.ValidationMessageFor(a => a.DbPassword)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.DbControlPassword)</td>
            <td>@Html.PasswordFor(a => a.DbControlPassword)</td>
            @Html.ValidationMessageFor(a => a.DbControlPassword)
        </tr>
        <tr>
            <td>
                <a href="/Vereniging/Index">
                    <input type="button" value="Back" />
                </a>
            </td>
            <td><input type="submit" value="Save" /></td>

        </tr>
    </table>
}

ITBedrijfProject/Views/Vereniging/EditRegister.cshtml
@model ITBedrijfProject.PresentationModels.PMOrganisationRegister
<h2>@ViewBag.Organisation.OrganisationName</h2>
<h3>Edit register</h3>
@using (Html.BeginForm("EditRegister", "Vereniging", FormMethod.Post))
{
    <input type="hidden" name="oldOrganisationID" id="oldOrganisationID" value="@ViewBag.oldId" />
    @Html.HiddenFor(a => a.RegisterID)
    @Html.HiddenFor(a => a.FromDate)
    @Html.HiddenFor(a => a.UntilDate)
    <table>
        <tr>
            <td>@Html.LabelFor(a => a.OrganisationName)</td>
            <td>@Html.DropDownListFor(a => a.OrganisationID, Model.NewOrganisation)</td>
            <td>@Html.ValidationMessageFor(a => a.OrganisationID)</td>
        </tr>
        <tr>
            <td>
                <a href="/Vereniging/Index">
                    <input type="button" value="Back" />
                </a>
            </td>
            <td><input type="submit" value="Save" /></td>

        </tr>
    </table>
}

ITBedrijfProject/Views/Vereniging/Index.cshtml
@model ITBedrijfProject.PresentationModels.PMIndex


@{
    ViewBag.Title = "Index";
}

<h2>Organisations</h2>
<p><a href="/Vereniging/NewOrganisation">New Organisation</a></p>
<table>
    <tr>
        <td width="200px">@Html.LabelFor(a => a.OrganisationName)</td>
        <td width="200px">@Html.LabelFor(a => a.Address)</td>
        <td width="200px">@Html.LabelFor(a => a.Email)</td>
        <td width="200px">@Html.LabelFor(a => a.Phone)</td>
    </tr>

    @foreach (var item in @ViewBag.Organisations)
    {
        <tr>
            <td>@item.OrganisationName</td>
            <td>@item.Address</td>
            <td>@item.Email</td>
            <td>@item.Phone</td>
            <td><a href="/Vereniging/Details?id=@item.Id">Details</a> | <a href="/Vereniging/Edit?id=@item.Id">Edit</a> | <a href="/Vereniging/Register?id=@item.Id">Registers</a> | <a href="/Vereniging/Delete?id=@item.Id">Delete</a>
        </tr>
    }

</table>

ITBedrijfProject/Views/Vereniging/NewOrganisation.cshtml
@model ITBedrijfProject.PresentationModels.PMOrganisation
@{
    ViewBag.Title = "NewOrganisation";
}

<h2>New Organisation</h2>
@using (Html.BeginForm("NewOrganisation", "Vereniging", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <table>
        <tr>
            <td>Persoonlijke Gegevens</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.OrganisationName)</td>
            <td>@Html.TextBoxFor(a => a.OrganisationName, new { placeholder = Html.DisplayNameFor(a => a.OrganisationName) })</td>
            @Html.ValidationMessageFor(a => a.OrganisationName)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Login)</td>
            <td>@Html.TextBoxFor(a => a.Login, new { placeholder = Html.DisplayNameFor(a => a.Login) })</td>
            @Html.ValidationMessageFor(a => a.Login)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Password)</td>
            <td>@Html.PasswordFor(a => a.Password, new { placeholder = Html.DisplayNameFor(a => a.Password) })</td>
            @Html.ValidationMessageFor(a => a.Password)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.ControlPassword)</td>
            <td>@Html.PasswordFor(a => a.ControlPassword, new { placeholder = Html.DisplayNameFor(a => a.ControlPassword) })</td>
            @Html.ValidationMessageFor(a => a.ControlPassword)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Address)</td>
            <td>@Html.TextBoxFor(a => a.Address, new { placeholder = Html.DisplayNameFor(a => a.Address) })</td>
            @Html.ValidationMessageFor(a => a.Address)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Email)</td>
            <td>@Html.TextBoxFor(a => a.Email, new { placeholder = Html.DisplayNameFor(a => a.Email) })</td>
            @Html.ValidationMessageFor(a => a.Email)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Phone)</td>
            <td>@Html.TextBoxFor(a => a.Phone, new { placeholder = Html.DisplayNameFor(a => a.Phone) })</td>
            @Html.ValidationMessageFor(a => a.Phone)
        </tr>

        <tr>
            <td>Database Gegevens</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.DbLogin)</td>
            <td>@Html.TextBoxFor(a => a.DbLogin, new { placeholder = Html.DisplayNameFor(a => a.DbLogin) })</td>
            @Html.ValidationMessageFor(a => a.DbLogin)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.DbName)</td>
            <td>@Html.TextBoxFor(a => a.DbName, new { placeholder = Html.DisplayNameFor(a => a.DbName) })</td>
            @Html.ValidationMessageFor(a => a.DbName)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.DbPassword)</td>
            <td>@Html.PasswordFor(a => a.DbPassword, new { placeholder = Html.DisplayNameFor(a => a.DbPassword) })</td>
            @Html.ValidationMessageFor(a => a.DbPassword)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.DbControlPassword)</td>
            <td>@Html.PasswordFor(a => a.DbControlPassword, new { placeholder = Html.DisplayNameFor(a => a.DbControlPassword) })</td>
            @Html.ValidationMessageFor(a => a.DbControlPassword)
        </tr>
        <tr>
            <td>
                <a href="/Vereniging/Index">
                    <input type="button" value="Back" />
                </a>
            </td>
            <td><input type="submit" value="Create" /></td>
           
        </tr>
    </table>

   
}

ITBedrijfProject/Views/Vereniging/NewRegister.cshtml
@model ITBedrijfProject.PresentationModels.PMOrganisationRegister
<h2>@ViewBag.Organisation.OrganisationName</h2>
<h3>Add register</h3>
@using (Html.BeginForm("NewRegister", "Vereniging", FormMethod.Post))
{
    @Html.HiddenFor(a => a.OrganisationID)
    <table>
        <tr>
            <td>@Html.LabelFor(a => a.RegisterName)</td>
            <td>@Html.DropDownListFor(a => a.RegisterID, Model.NewRegister)</td>
            <td>@Html.ValidationMessageFor(a => a.RegisterID)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.FromDate)</td>
            <td><input type="date" value="@DateTime.Today" id="FromDate" name="FromDate" min="@DateTime.Today.Year-@DateTime.Today.Month-@DateTime.Today.Day" /></td>
            <td><input type="time" value="@DateTime.Today" id="FromTime" name="FromTime" /></td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.UntilDate)</td>
            <td><input type="date" value="@DateTime.Today" id="UntilDate" name="UntilDate" min="@DateTime.Today.Year-@DateTime.Today.Month-@DateTime.Today.Day" /></td>
            <td><input type="time" value="@DateTime.Today" id="UntilTime" name="UntilTime" /></td>
        </tr>
        <tr>
            <td>
                <a href="/Vereniging/Index">
                    <input type="button" value="Back" />
                </a>
            </td>
            <td><input type="submit" value="Create" /></td>

        </tr>
    </table>
}

ITBedrijfProject/Views/Vereniging/Register.cshtml
@model ITBedrijfProject.PresentationModels.PMOrganisationRegister
<h2>@ViewBag.Organisation.OrganisationName</h2>
<h3>Registers</h3>
@using (Html.BeginForm("Index", "Vereniging", FormMethod.Post))
{
    <p><a href="/Vereniging/NewRegister?id=@ViewBag.Organisation.Id">Add register</a></p>
<table>
    <tr>
        <td width="200px">@Html.LabelFor(a => a.RegisterName)</td>
        <td width="200px">@Html.LabelFor(a => a.Device)</td>
        <td width="200px">@Html.LabelFor(a => a.FromDate)</td>
        <td width="200px">@Html.LabelFor(a => a.UntilDate)</td>
    </tr>
    @foreach (var item in @ViewBag.Register)
    {
        <tr>
            <td>@item.RegisterName</td>
            <td>@item.Device</td>
            <td>@item.FromDate</td>
            <td>@item.UntilDate</td>
            <td><a href="/Vereniging/EditRegister?organisationID=@ViewBag.Organisation.Id&registerID=@item.RegisterID">Edit</a></td>
        </tr>
    }
</table>

<input type="submit" name="Back" value="Back" />
}