ITBedrijfProject/Controllers/KassaController.cs
using ITBedrijfProject.DataAcces;
using ITBedrijfProject.Models;
using ITBedrijfProject.PresentationModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ITBedrijfProject.Controllers
{
    public class KassaController : Controller
    {
        // GET: Kassa
        public ActionResult Index()
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            List<Register> registers = DARegister.GetRegisters();
            ViewBag.Registers = registers;
            return View();
        }

        [HttpGet]
        public ActionResult NewRegister()
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            //var context = new ApplicationDbContext();
            //ViewBag.Users = context.Users;
            return View();
        }

        [HttpPost]
        public ActionResult NewRegister(PMRegister register)
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            if (ModelState.IsValid)
            {
                if (register.PurchaseDate >= register.ExpiresDate) return View(register);
                DARegister.InsertRegister(register);
                return RedirectToAction("Index");
            }
            return View(register);
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            Register register = DARegister.GetRegisterById(id);
            ViewBag.Register = register;
            ViewBag.Id = id;
            return View(register);
        }

        [HttpPost]
        public ActionResult Details()
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            return View("Index");
        }

        [HttpGet]
        public ActionResult Logs(int id)
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            Register register = DARegister.GetRegisterById(id);
            ViewBag.Register = register;

           List<Errorlog> log = DAErrorLog.GetLogsById(id);
             ViewBag.Log = log;
             ViewBag.Id = id;
             return View();
        }

        [HttpPost]
        public ActionResult Logs()
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            return View("Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            Register register = DARegister.GetRegisterById(id);
            return View(register);
        }

        //Dit wordt uitgevoerd wanneer er op de deleteknop gedrukt wordt 
        [HttpPost]
        public ActionResult DeleteItem(int Id)
        {
            DARegister.DeleteRegister(Id);

            return RedirectToAction("Index");


        }
    
    }
}

ITBedrijfProject/Views/Kassa/Delete.cshtml
@model ITBedrijfProject.Models.Register

<h2>Do you want to delete this register?</h2>

@using (Html.BeginForm("DeleteItem", "Kassa", FormMethod.Post))
{
    @Html.HiddenFor(a => a.Id)
    @Html.HiddenFor(a => a.Id);

    <table>
        <tr>
            <td>@Html.LabelFor(a => a.RegisterName)</td>
            <td>@Html.ValueFor(a => a.RegisterName)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Device)</td>
            <td>@Html.ValueFor(a => a.Device)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.PurchaseDate)</td>
            <td>@Html.ValueFor(a => a.PurchaseDate)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.ExpiresDate)</td>
            <td>@Html.ValueFor(a => a.ExpiresDate)</td>
        </tr>

        <tr>
            <td>
                <a href="/Kassa/Index">
                    <input type="button" value="Back" />
                </a>
            </td>
            <td><input type="submit" value="Delete" /></td>

        </tr>
    </table>
}

ITBedrijfProject/Views/Kassa/Details.cshtml
@model ITBedrijfProject.Models.Register

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

@using (Html.BeginForm("Index", "Kassa", FormMethod.Post))
{
    @Html.HiddenFor(a => a.Id);
    
    <table>
        <tr>
            <td>@Html.LabelFor(a => a.RegisterName)</td>
            <td>@Html.ValueFor(a => a.RegisterName)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Device)</td>
            <td>@Html.ValueFor(a => a.Device)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.PurchaseDate)</td>
            <td>@Html.ValueFor(a => a.PurchaseDate)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.ExpiresDate)</td>
            <td>@Html.ValueFor(a => a.ExpiresDate)</td>
        </tr>
        
    </table>
    
                <br />
        <input type="submit" name="Back" value="Back" />
}

ITBedrijfProject/Views/Kassa/Index.cshtml
@model ITBedrijfProject.Models.Register

@{
    ViewBag.Title = "Index";
}

<h2>Registers</h2>
<p><a href="/Kassa/NewRegister">Nieuwe kassa</a></p>
<table>
    <tr>
        <td width="200px">@Html.LabelFor(a => a.RegisterName)</td>
        <td width="200px">@Html.LabelFor(a => a.Device)</td>
        <td width="200px">@Html.LabelFor(a => a.PurchaseDate)</td>
        <td width="200px">@Html.LabelFor(a => a.ExpiresDate)</td>
    </tr>

    @foreach (var item in @ViewBag.Registers)
    {
        <tr>
            <td>@item.RegisterName</td>
            <td>@item.Device</td>
            <td>@item.PurchaseDate</td>
            <td>@item.ExpiresDate</td>
            <td><a href="/Kassa/Details?id=@item.Id">Details</a> | <a href="/Kassa/Edit?id=@item.Id">Edit</a> | <a href="/Kassa/Logs?id=@item.Id">Logs</a> | <a href="/Kassa/Delete?id=@item.Id">Delete</a>
        </tr>
    }

</table>

ITBedrijfProject/Views/Kassa/Logs.cshtml
@model ITBedrijfProject.Models.Errorlog

@{
    ViewBag.Title = "Logs";
}
<h2>@ViewBag.Register.RegisterName</h2>
<h3>Logs</h3>

@using (Html.BeginForm("Index", "Kassa", FormMethod.Post))
{
    <table>
        <tr>
            <td width="200px">@Html.LabelFor(a => a.Timestamp)</td>
            <td width="200px">@Html.LabelFor(a => a.Message)</td>
            <td width="200px">@Html.LabelFor(a => a.Stacktrace)</td>
        </tr>

        @foreach (var item in @ViewBag.Log)
        {
            <tr>
                <td>@item.Timestamp</td>
                <td>@item.Message</td>
                <td>@item.Stacktrace</td>
            </tr>
        }

        </table>

    <br />
    <input type="submit" name="Back" value="Back" />
}

ITBedrijfProject/Views/Kassa/NewRegister.cshtml
@model ITBedrijfProject.PresentationModels.PMRegister


@{
    ViewBag.Title = "NewRegister";
}

<h2>New Register</h2>

@using (Html.BeginForm("NewRegister", "Kassa", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <table>
        <tr>
            <td>@Html.LabelFor(a => a.RegisterName)</td>
            <td>@Html.TextBoxFor(a => a.RegisterName, new { placeholder = Html.DisplayNameFor(a => a.RegisterName) })</td>
            @Html.ValidationMessageFor(a => a.RegisterName)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Device)</td>
            <td>@Html.TextBoxFor(a => a.Device, new { placeholder = Html.DisplayNameFor(a => a.Device) })</td>
            @Html.ValidationMessageFor(a => a.Device)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.PurchaseDate)</td>
            <td><input type="date" value="@DateTime.Today" id="PurchaseDate" name="PurchaseDate" min="@DateTime.Today.Year-@DateTime.Today.Month-@DateTime.Today.Day" /></td>
            <td><input type="time" value="@DateTime.Today" id="PurchaseTime" name="PurchaseTime" /></td>
            @Html.ValidationMessageFor(a => a.PurchaseDate)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.ExpiresDate)</td>
            <td><input type="date" value="@DateTime.Today" id="ExpiresDate" name="ExpiresDate" min="@DateTime.Today.AddDays(1).Year-@DateTime.Today.AddDays(1).Month-@DateTime.Today.AddDays(1).Day" /></td>
            <td><input type="time" value="@DateTime.Today" id="ExpiresTime" name="ExpiresTime" /></td>
            @Html.ValidationMessageFor(a => a.ExpiresDate)
        </tr>
        <tr>
            <td>
                <a href="/Kassa/Index">
                    <input type="button" value="Back" />
                </a>
            </td>
            <td><input type="submit" value="Create" /></td>

        </tr>
    </table>
}